version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: pingmottu-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: ["mongod", "--bind_ip_all"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pingmottu-api
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://admin:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/admin
      - Mongo__DatabaseName=${MONGO_INITDB_DATABASE}
      - Jwt__Secret=${JWT_SECRET}
    ports:
      - "5264:80"
    volumes:
      - ./:/app
    networks:
      - pingnet

volumes:
  mongo-data:

networks:
  pingnet:
